title: Ctrl + Alt + Career
author: Jennifer Ong
email: j.ong1222@gmail.com
description: >-
  Ctrl + Alt + Career goes behind the scenes of people who have embarked on an alternative career in Asia 
  and the challenges they face in a society where we are often expected to follow a traditional career path.
subtitle: >-
  Behind the scenes of people who have embarked on an alternative career in Asia
lang: en-us
copyright: "&#xA9; 2020 Ctrl + Alt + Career"
logo: assets/img/logo.png
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
