title: CollierCast Podcast
description: You'll hear us talk about amazing things!
author: Colliercast
email: colliercast@gaggle.email
lang: en-us
copyright: "&#x2117; &amp; CollierCast &#xA9; 2020"
logo: /assets/img/logo.png
 baseurl: "/podcast/" # the subpath of your site, e.g. /blog
 url: "https://opticdigital.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
